### PR TITLE
Improvements to Sinitic languages and script names

### LINKED ISSUE #1410: Stop using "Chinese (language name, script/variant name)" as the main name for languages under Sinitic language group
### Describe the problem

Currently, most languages under Sinitic language group are having "Chinese (language name, script/variant name)"-style names.

However, this would be confusing as:

- We mostly only use "Chinese" to refer "Mandarin"/"Cantonese".
- Only writing "Simplified" does not indicate the difference is based on script (writing system).

For example, `gan` "Gan" (preferred solution) / "Gan Chinese" (alternative solution) / "Chinese (Gan)" (confusing option)

### Describe the solution you would like

- `cdo-Hans` "Mindong (Simplified Han script)"
- `cdo-Hant` "Mindong (Traditional Han script)"
- `cdo-Latn` "Mindong (Latin script)"
- `cpx-Hans` "Pu–Xian Min (Simplified Han script)"
- `cpx-Hant` "Pu–Xian Min (Traditional Han script)"
- `cpx-Latn` "Pu–Xian Min (Latin script)"
- `gan-Hans` "Gan (Simplified Han script)"
- `gan-Hant` "Gan (Traditional Han script)"
- `hak-Hans` "Hakka (Simplified Han script)"
- `hak-Hant` "Hakka (Traditional Han script)"
- `hak-Latn` "Hakka (Latin script)"
- `hsn` "Xiang"
- `lzh` "Literary Chinese"
- `nan-Hant` "Hokkien (Traditional Han script)"
- `nan-Latn-pehoeji` "Hokkien (Pe̍h-ōe-jī)"
- `nan-Latn-tailo` "Hokkien (Tâi-lô)"
- `wuu-Hans` "Wu (Simplified Han script)"
- `wuu-Hant` "Wu (Traditional Han script)"
- `yue-Hans` "Cantonese (Simplified Han script)"
- `yue-Hant` "Cantonese (Traditional Han script)"
- `zh-Hans` "Chinese (Traditional Han script)"
- `zh-Hans-SG` "Chinese (Traditional Han script, Singapore)"
- `zh-Hant` "Chinese (Traditional Han script)"
- `zh-Hant-HK` "Chinese (Traditional Han script, Hong Kong)"
- `zh-Latn-CN` "Chinese (Hanyu Pinyin, Mainland China)"
- `zh-Latn-TW-pinyin` "Chinese (Hanyu Pinyin, Taiwan)"
- `zh-Latn-TW-tongyong` "Chinese (Tongyong Pinyin, Taiwan)"
- `zh-Latn-TW-wadegile` "Chinese (Wade–Giles, Taiwan)"

### Describe alternatives you have considered

- `cdo-Hans` "Mindong (Simplified Han)"
- `cdo-Hant` "Mindong (Traditional Han)"
- `cdo-Latn` "Mindong (Latin)"
- `cpx-Hans` "Pu–Xian Min (Simplified Han)"
- `cpx-Hant` "Pu–Xian Min (Traditional Han)"
- `cpx-Latn` "Pu–Xian Min (Latin)"
- `gan-Hans` "Gan (Simplified Han)"
- `gan-Hant` "Gan (Traditional Han)"
- `hak-Hans` "Hakka (Simplified Han)"
- `hak-Hant` "Hakka (Traditional Han)"
- `hak-Latn` "Hakka (Latin)"
- `hsn` "Xiang"
- `lzh` "Literary Chinese"
- `nan-Hant` "Hokkien (Traditional Han)"
- `nan-Latn-pehoeji` "Hokkien (Pe̍h-ōe-jī)"
- `nan-Latn-tailo` "Hokkien (Tâi-lô)"
- `wuu-Hans` "Wu (Simplified Han)"
- `wuu-Hant` "Wu (Traditional Han)"
- `yue-Hans` "Cantonese (Simplified Han)"
- `yue-Hant` "Cantonese (Traditional Han)"
- `zh-Hans` "Chinese (Traditional Han)"
- `zh-Hans-SG` "Chinese (Traditional Han, Singapore)"
- `zh-Hant` "Chinese (Traditional Han)"
- `zh-Hant-HK` "Chinese (Traditional Han, Hong Kong)"
- `zh-Latn-CN` "Chinese (Hanyu Pinyin, Mainland China)"
- `zh-Latn-TW-pinyin` "Chinese (Hanyu Pinyin, Taiwan)"
- `zh-Latn-TW-tongyong` "Chinese (Tongyong Pinyin, Taiwan)"
- `zh-Latn-TW-wadegile` "Chinese (Wade–Giles, Taiwan)"

### Screenshots

_No response_

### Additional context

_No response_

### LINKED ISSUE #1411: Split "gan" into "gan-Hant", "gan-Hans"
### Describe the problem

Currently Gan language(s) has 2 written scripts.

Some people use Traditional Han script (characters), while others use Simplified Han script.

### Describe the solution you would like

- Split "gan" into "gan-Hant", "gan-Hans".
- Redirect "gan" to "gan-Hant".

### Describe alternatives you have considered

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by winstonsung**
closes #1410
closes #1411

Bug: #1410
Bug: #1411
Change-Id: Ibc4e7802d6a331511792da37824378074722c5c0

## Proposed changes

- Use "language name (script/orthography name)" instead of "Chinese (language name, script/orthography name)"
- Add Sinitic languages
- Add Formosan languages (Taiwanese aboriginal languages)
- Split gan into gan-Hans, gan-Hant
- Split hak into hak-Hans, hak-Hant, hak-Latn

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

### CODE REVIEW

**Comment by winstonsung** [comment]
> @nijel wrote:
> Pull requests are welcome! Master language definitions are at https://github.com/WeblateOrg/language-data/blob/main/languages.csv

Thanks. However, not all
```
weblate_language_data\locale\*\LC_MESSAGES\django.po
```
files were updated when using
```bash
make
```
(especially for those language tag with underscores), any ideas about the issue (or is it intended)?

**Comment by nijel** [comment]
There was missing alias for `hak`, I've added it in d8b763ae to `hak_Hant`. Please correct that if it's wrong.

As for missed updates, it should be fixed by 4458b61a8e2483a8b4f40ec5054de1c89a58e4c8, thanks for spotting!

**Comment by winstonsung** [comment]
> There was missing alias for `hak`, I've added it in [d8b763a](https://github.com/WeblateOrg/language-data/commit/d8b763ae0ae289c5f8743a33d48bb49bacbc710c) to `hak_Hant`. Please correct that if it's wrong.

It's correct. Thanks.

> As for missed updates, it should be fixed by [4458b61](https://github.com/WeblateOrg/language-data/commit/4458b61a8e2483a8b4f40ec5054de1c89a58e4c8), thanks for spotting!

Thanks for the fix.

**Comment by winstonsung** [comment]
```
Rebasing (1/1)
Auto-merging weblate_language_data/locale/fr/LC_MESSAGES/django.po
CONFLICT (content): Merge conflict in weblate_language_data/locale/fr/LC_MESSAGES/django.po
error: could not apply 23460f26... Translated using Weblate (French)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 23460f26... Translated using Weblate (French)
 (1)
 ```

**Pull request merged**
